site_name: LDA++
site_favicon: img/favicon.png
repo_url: https://github.com/angeloskath/supervised-lda
theme_dir: docs/custom_theme
pages:
- Home: index.md
- Getting Started: getting-started.md
- Parameters: parameters.md
include_nav: true
