site_name: LDA++
site_favicon: img/favicon.png
repo_url: https://github.com/angeloskath/supervised-lda
google_analytics: ["UA-84658266-1", "auto"]
theme_dir: docs/custom_theme
docs_dir: docs/site
site_dir: docs/output
pages:
- Home: index.md
- Documentation:
  - Installation: installation.md
  - Console applications: console-applications.md
  - Getting started: getting-started.md
- Examples:
  - Visualize topics from MNIST: mnist-example.md
  - Topic inference visualization: topic-inference-visualization.md
include_nav: true
